name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


jobs:
  draft-new-release:
    uses: tirazel/actions-collection/.github/workflows/draft-release.yml@main